'use client';
import {useEffect,useState} from 'react';
type Wish={id:number;name:string;quantity:number;unit:string;imageKey:string|null};
type Item={id:number;name:string;unit:string;packedQuantity:number;hasStock:boolean};
export default function Portal(){
 const [wishes,setWishes]=useState<Wish[]>([]),[items,setItems]=useState<Item[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[token,setToken]=useState('');
 const [requester,setRequester]=useState(''),[name,setName]=useState(''),[quantity,setQuantity]=useState(1),[unit,setUnit]=useState('Stück'),[photo,setPhoto]=useState<File|null>(null),[fileKey,setFileKey]=useState(0);
 async function load(q:string,signal?:AbortSignal){const r=await fetch('/api/portal?q='+encodeURIComponent(q),{cache:'no-store',signal});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setWishes(d.wishes);setItems(d.materials);}
 useEffect(()=>{setToken(crypto.randomUUID());},[]);
 useEffect(()=>{const abort=new AbortController();const timer=setTimeout(()=>{setLoading(true);load(query,abort.signal).then(()=>setError('')).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});},250);return()=>{clearTimeout(timer);abort.abort();};},[query]);
 useEffect(()=>{const id=setInterval(()=>load(query).catch(()=>{}),30000);return()=>clearInterval(id);},[query]);
 const grouped=Object.values(wishes.reduce((a,w)=>{const key=w.name+'|'+w.unit;if(!a[key])a[key]={name:w.name,unit:w.unit,quantity:0,images:[] as string[]};a[key].quantity+=w.quantity;if(w.imageKey)a[key].images.push(w.imageKey);return a;},{} as Record<string,{name:string;unit:string;quantity:number;images:string[]}>));
 return <main className="portal"><header className="portal-brand"><img src="/jugend-logo.svg" alt="jung+ev."/><div><strong>Ev. Jugend Lauenburg<sup>4</sup></strong><span>KonfiCamp · Camp-Portal</span></div></header><h1>Was brauchen wir noch?</h1><p className="portal-intro">Einkaufswünsche teilen und nachsehen, welches Material für das Camp gepackt wurde.</p>
 {error&&<div role="alert" className="portal-alert">{error}<button onClick={()=>load(query).catch(e=>setError(e.message))}>Erneut laden</button></div>}{notice&&<div role="status" className="portal-success">{notice}</div>}
 <section className="portal-card"><h2>Haben wir das dabei?</h2><label>Material suchen<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Zum Beispiel Beamer, Kabel oder Schere"/></label>{query.trim()&&(loading?<p>Suche …</p>:items.length?<ul className="portal-list">{items.map(m=><li key={m.id}><strong>{m.name}</strong><span className={m.packedQuantity?'portal-status yes':'portal-status'}>{m.packedQuantity?`Dabei · ${m.packedQuantity} ${m.unit} als gepackt markiert`:m.hasStock?'Bestand vorhanden · noch nicht als gepackt markiert':'Kein Bestand hinterlegt'}</span></li>)}</ul>:<p>Kein passendes Material gefunden.</p>)}<p className="portal-help">„Dabei“ basiert auf dem Häkchen in der Packliste. Der tatsächliche Transport wird damit nicht separat bestätigt.</p></section>
 <section className="portal-card"><h2>Einkaufswunsch eintragen</h2><form onSubmit={async e=>{e.preventDefault();if(saving)return;setSaving(true);setError('');setNotice('');try{const f=new FormData();f.set('requester',requester);f.set('name',name);f.set('quantity',String(quantity));f.set('unit',unit);f.set('requestKey',token);if(photo)f.set('photo',photo);const r=await fetch('/api/portal',{method:'POST',body:f});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setName('');setQuantity(1);setPhoto(null);setFileKey(n=>n+1);setToken(crypto.randomUUID());setNotice('Dein Wunsch wurde aufgenommen. Danke!');await load(query);}catch(e){setError(e instanceof Error?e.message:'Speichern fehlgeschlagen.');}finally{setSaving(false);}}}>
 <label>Von wem kommt der Wunsch? *<input required maxLength={100} value={requester} onChange={e=>setRequester(e.target.value)} placeholder="Dein Name" autoComplete="name"/></label><label>Was soll besorgt werden? *<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Zum Beispiel Apfelsaft"/></label><div className="portal-form-row"><label>Menge *<input required type="number" min={1} max={100000} step={1} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>Mengeneinheit *<input required maxLength={30} value={unit} onChange={e=>setUnit(e.target.value)} placeholder="Flaschen, Packungen …"/></label></div><label>Bild als Einkaufsvorlage (optional)<input key={fileKey} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label><p className="portal-help">JPG, PNG oder WebP · maximal 5 MB. Die Einkaufsvorlage ist im Portal sichtbar.</p><button className="button primary" disabled={saving||!token}>{saving?'Wird gespeichert …':'Wunsch abschicken'}</button></form></section>
 <section className="portal-card"><h2>Offene Einkaufswünsche <span className="count">{grouped.length}</span></h2><p>Hier stehen ausschließlich Wünsche aus diesem Portal. Sobald Bestand eingetragen wird, verschwindet der Wunsch aus der Liste.</p>{grouped.length?<ul className="portal-list">{grouped.map(w=><li key={w.name+'|'+w.unit}><div><strong>{w.name}</strong><span>{w.quantity} {w.unit}</span></div>{w.images.map(key=><a key={key} href={'/api/portal/photo?id='+key} target="_blank" rel="noopener noreferrer"><img className="portal-photo" src={'/api/portal/photo?id='+key} alt={'Einkaufsvorlage für '+w.name}/></a>)}</li>)}</ul>:<p>{loading?'Wünsche werden geladen …':'Aktuell sind keine Einkaufswünsche offen.'}</p>}</section><footer className="portal-footer"><a href="/">Zur geschützten Verwaltung</a></footer></main>;
}
